<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/
Route::group(['middleware' => 'cros'], function ()
{
Route::post('user_login',[App\Http\Controllers\api\user\userscontroller::class,'user_login']);
Route::group(['middleware' => ['auth:sanctum']], function() {
Route::get('user_logout',[App\Http\Controllers\api\user\userscontroller::class,'user_logout']);
});
Route::post('role_create',[App\Http\Controllers\api\role\rolecontroller::class,'role_create']);
Route::post('role_edit',[App\Http\Controllers\api\role\rolecontroller::class,'role_edit']);
Route::get('role_list',[App\Http\Controllers\api\role\rolecontroller::class,'role_list']);
Route::post('role_delete',[App\Http\Controllers\api\role\rolecontroller::class,'role_delete']);
Route::post('user_insert',[App\Http\Controllers\api\user\userscontroller::class,'user_insert']);
Route::get('user_list',[App\Http\Controllers\api\user\userscontroller::class,'user_list']);
Route::post('user_edit',[App\Http\Controllers\api\user\userscontroller::class,'user_edit']);
Route::post('user_delete',[App\Http\Controllers\api\user\userscontroller::class,'user_delete']);
Route::post('system_setting_create',[App\Http\Controllers\api\system_settings\system_setting::class,'system_setting_create']);
Route::post('system_setting_edit',[App\Http\Controllers\api\system_settings\system_setting::class,'system_setting_edit']);
Route::get('system_setting_list',[App\Http\Controllers\api\system_settings\system_setting::class,'system_setting_list']);
Route::post('system_setting_delete',[App\Http\Controllers\api\system_settings\system_setting::class,'system_setting_delete']);
Route::post('course_create',[App\Http\Controllers\api\course\coursecontroller::class,'course_create']);
Route::post('course_edit',[App\Http\Controllers\api\course\coursecontroller::class,'course_edit']);
Route::get('course_list',[App\Http\Controllers\api\course\coursecontroller::class,'course_list']);
Route::post('course_delete',[App\Http\Controllers\api\course\coursecontroller::class,'course_delete']);
Route::post('category_create',[App\Http\Controllers\api\category\categorycontroller::class,'category_create']);
Route::post('category_edit',[App\Http\Controllers\api\category\categorycontroller::class,'category_edit']);
Route::get('category_show',[App\Http\Controllers\api\category\categorycontroller::class,'category_show']);
Route::post('category_delete',[App\Http\Controllers\api\category\categorycontroller::class,'category_delete']);
Route::post('language_create',[App\Http\Controllers\api\language\languagecontroller::class,'language_create']);
Route::get('language_list',[App\Http\Controllers\api\language\languagecontroller::class,'language_list']);
Route::post('language_delete',[App\Http\Controllers\api\language\languagecontroller::class,'language_delete']);
Route::post('main_category_store',[App\Http\Controllers\api\main_category\main_categorycontroller::class,'main_category_store']);
Route::post('main_category_edit',[App\Http\Controllers\api\main_category\main_categorycontroller::class,'main_category_edit']);
Route::get('main_category_list',[App\Http\Controllers\api\main_category\main_categorycontroller::class,'main_category_list']);
Route::post('main_category_delete',[App\Http\Controllers\api\main_category\main_categorycontroller::class,'main_category_delete']);
Route::post('sub_category_store',[App\Http\Controllers\api\sub_category\sub_categorycontroller::class,'sub_category_store']);
Route::post('sub_category_edit',[App\Http\Controllers\api\sub_category\sub_categorycontroller::class,'sub_category_edit']);
Route::get('sub_category_list',[App\Http\Controllers\api\sub_category\sub_categorycontroller::class,'sub_category_list']);
Route::post('sub_category_delete',[App\Http\Controllers\api\sub_category\sub_categorycontroller::class,'sub_category_delete']);
Route::post('child_category_store',[App\Http\Controllers\api\child_category\child_categorycontroller::class,'child_category_store']);
Route::post('child_category_edit',[App\Http\Controllers\api\child_category\child_categorycontroller::class,'child_category_edit']);
Route::get('child_category_list',[App\Http\Controllers\api\child_category\child_categorycontroller::class,'child_category_list']);
Route::post('child_category_delete',[App\Http\Controllers\api\child_category\child_categorycontroller::class,'child_category_delete']);
Route::post('lession_store',[App\Http\Controllers\api\lession\lessioncontroller::class,'lession_store']);
Route::post('lession_edit',[App\Http\Controllers\api\lession\lessioncontroller::class,'lession_edit']);
Route::post('lession_list',[App\Http\Controllers\api\lession\lessioncontroller::class,'lession_list']);
Route::post('lession_delete',[App\Http\Controllers\api\lession\lessioncontroller::class,'lession_delete']);
Route::post('module_store',[App\Http\Controllers\api\modules\modulecontroller::class,'module_store']);
Route::post('module_edit',[App\Http\Controllers\api\modules\modulecontroller::class,'module_edit']);
Route::post('module_list',[App\Http\Controllers\api\modules\modulecontroller::class,'module_list']);
Route::post('module_delete',[App\Http\Controllers\api\modules\modulecontroller::class,'module_delete']);
Route::post('teacher_store',[App\Http\Controllers\api\teacher\teachercontroller::class,'teacher_store']);
Route::get('teacher_list',[App\Http\Controllers\api\teacher\teachercontroller::class,'teacher_list']);
Route::post('teacher_delete',[App\Http\Controllers\api\teacher\teachercontroller::class,'teacher_delete']);
Route::post('subject_store',[App\Http\Controllers\api\subject\subjectcontroller::class,'subject_store']);
Route::post('subject_edit',[App\Http\Controllers\api\subject\subjectcontroller::class,'subject_edit']);
Route::post('subject_list',[App\Http\Controllers\api\subject\subjectcontroller::class,'subject_list']);
Route::post('subject_delete',[App\Http\Controllers\api\subject\subjectcontroller::class,'subject_delete']);
Route::post('course_video_store',[App\Http\Controllers\api\add_lecture\coursevideo::class,'course_video_store']);
Route::post('course_video_edit',[App\Http\Controllers\api\add_lecture\coursevideo::class,'course_video_edit']);
Route::get('course_video_show',[App\Http\Controllers\api\add_lecture\coursevideo::class,'course_video_show']);
Route::post('course_video_delete',[App\Http\Controllers\api\add_lecture\coursevideo::class,'course_video_delete']);
Route::post('video_store',[App\Http\Controllers\api\add_lecture\videocontroller::class,'video_store']);
Route::post('video_edit',[App\Http\Controllers\api\add_lecture\videocontroller::class,'video_edit']);
Route::get('video_show',[App\Http\Controllers\api\add_lecture\videocontroller::class,'video_show']);
Route::post('video_delete',[App\Http\Controllers\api\add_lecture\videocontroller::class,'video_delete']);
Route::post('audio_store',[App\Http\Controllers\api\add_lecture\audiocontroller::class,'audio_store']);
Route::post('audio_edit',[App\Http\Controllers\api\add_lecture\audiocontroller::class,'audio_edit']);
Route::get('audio_show',[App\Http\Controllers\api\add_lecture\audiocontroller::class,'audio_show']);
Route::post('audio_delete',[App\Http\Controllers\api\add_lecture\audiocontroller::class,'audio_delete']);
Route::post('document_store',[App\Http\Controllers\api\add_lecture\documentcontroller::class,'document_store']);
Route::post('document_edit',[App\Http\Controllers\api\add_lecture\documentcontroller::class,'document_edit']);
Route::get('document_show',[App\Http\Controllers\api\add_lecture\documentcontroller::class,'document_show']);
Route::post('document_delete',[App\Http\Controllers\api\add_lecture\documentcontroller::class,'document_delete']);
Route::post('text_store',[App\Http\Controllers\api\add_lecture\textcontroller::class,'text_store']);
Route::post('text_edit',[App\Http\Controllers\api\add_lecture\textcontroller::class,'text_edit']);
Route::get('text_show',[App\Http\Controllers\api\add_lecture\textcontroller::class,'text_show']);
Route::post('text_delete',[App\Http\Controllers\api\add_lecture\textcontroller::class,'text_delete']);
Route::post('image_store',[App\Http\Controllers\api\add_lecture\imagecontroller::class,'image_store']);
Route::post('image_edit',[App\Http\Controllers\api\add_lecture\imagecontroller::class,'image_edit']);
Route::get('image_show',[App\Http\Controllers\api\add_lecture\imagecontroller::class,'image_show']);
Route::post('image_delete',[App\Http\Controllers\api\add_lecture\imagecontroller::class,'image_delete']);
Route::post('other_video_store',[App\Http\Controllers\api\add_lecture\othercontroller::class,'other_video_store']);
Route::post('other_video_edit',[App\Http\Controllers\api\add_lecture\othercontroller::class,'other_video_edit']);
Route::get('other_video_show',[App\Http\Controllers\api\add_lecture\othercontroller::class,'other_video_show']);
Route::post('other_video_delete',[App\Http\Controllers\api\add_lecture\othercontroller::class,'other_video_delete']);
Route::post('assessment_store',[App\Http\Controllers\api\add_assessment\assessmentcontroller::class,'assessment_store']);
Route::post('assessment_edit',[App\Http\Controllers\api\add_assessment\assessmentcontroller::class,'assessment_edit']);
Route::get('assessment_show',[App\Http\Controllers\api\add_assessment\assessmentcontroller::class,'assessment_show']);
Route::post('assessment_delete',[App\Http\Controllers\api\add_assessment\assessmentcontroller::class,'assessment_delete']);
Route::post('homework_store',[App\Http\Controllers\api\add_homework\homeworkcontroller::class,'homework_store']);
Route::post('homework_edit',[App\Http\Controllers\api\add_homework\homeworkcontroller::class,'homework_edit']);
Route::get('homework_show',[App\Http\Controllers\api\add_homework\homeworkcontroller::class,'homework_show']);
Route::post('homework_delete',[App\Http\Controllers\api\add_homework\homeworkcontroller::class,'homework_delete']);
Route::post('text_homework_store',[App\Http\Controllers\api\add_homework\textcontroller::class,'text_homework_store']);
Route::post('text_homework_edit',[App\Http\Controllers\api\add_homework\textcontroller::class,'text_homework_edit']);
Route::get('text_homework_show',[App\Http\Controllers\api\add_homework\textcontroller::class,'text_homework_show']);
Route::post('text_homework_delete',[App\Http\Controllers\api\add_homework\textcontroller::class,'text_homework_delete']);
Route::post('multiple_choice_store',[App\Http\Controllers\api\add_homework\multiplecontroller::class,'multiple_choice_store']);
Route::post('multiple_choice_edit',[App\Http\Controllers\api\add_homework\multiplecontroller::class,'multiple_choice_edit']);
Route::get('multiple_choice_show',[App\Http\Controllers\api\add_homework\multiplecontroller::class,'multiple_choice_show']);
Route::post('multiple_choice_delete',[App\Http\Controllers\api\add_homework\multiplecontroller::class,'multiple_choice_delete']);
Route::post('document_homework_store',[App\Http\Controllers\api\add_homework\documentcontroller::class,'document_homework_store']);
Route::post('document_homework_edit',[App\Http\Controllers\api\add_homework\documentcontroller::class,'document_homework_edit']);
Route::get('document_homework_show',[App\Http\Controllers\api\add_homework\documentcontroller::class,'document_homework_show']);
Route::post('document_homework_delete',[App\Http\Controllers\api\add_homework\documentcontroller::class,'document_homework_delete']);
Route::post('video_homework_store',[App\Http\Controllers\api\add_homework\videocontroller::class,'video_homework_store']);
Route::post('video_homework_edit',[App\Http\Controllers\api\add_homework\videocontroller::class,'video_homework_edit']);
Route::get('video_homework_show',[App\Http\Controllers\api\add_homework\videocontroller::class,'video_homework_show']);
Route::post('video_homework_delete',[App\Http\Controllers\api\add_homework\videocontroller::class,'video_homework_delete']);
Route::post('smtp_setting_store',[App\Http\Controllers\api\smtp_setting\smtpcontroller::class,'smtp_setting_store']);
Route::post('smtp_setting_edit',[App\Http\Controllers\api\smtp_setting\smtpcontroller::class,'smtp_setting_edit']);
Route::get('smtp_setting_list',[App\Http\Controllers\api\smtp_setting\smtpcontroller::class,'smtp_setting_list']);
Route::post('smtp_setting_delete',[App\Http\Controllers\api\smtp_setting\smtpcontroller::class,'smtp_setting_delete']);
Route::post('site_setting_store',[App\Http\Controllers\api\site_settings\sitecontroller::class,'site_setting_store']);
Route::post('site_setting_edit',[App\Http\Controllers\api\site_settings\sitecontroller::class,'site_setting_edit']);
Route::get('site_setting_list',[App\Http\Controllers\api\site_settings\sitecontroller::class,'site_setting_list']);
Route::post('site_setting_delete',[App\Http\Controllers\api\site_settings\sitecontroller::class,'site_setting_delete']);
Route::post('permission_store',[App\Http\Controllers\api\permission\permisioncontroller::class,'permission_store']);
Route::post('permission_edit',[App\Http\Controllers\api\permission\permisioncontroller::class,'permission_edit']);
Route::get('permission_list',[App\Http\Controllers\api\permission\permisioncontroller::class,'permission_list']);
Route::post('permission_delete',[App\Http\Controllers\api\permission\permisioncontroller::class,'permission_delete']);
Route::post('course_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'course_filter']);
Route::post('user_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'user_filter']);
Route::post('main_category_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'main_category_filter']);
Route::post('sub_category_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'sub_category_filter']);
Route::post('child_category_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'child_category_filter']);
Route::post('subject_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'subject_filter']);
Route::post('modules_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'modules_filter']);
Route::post('lession_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'lession_filter']);

////////////////forntend....................................
Route::post('admin_signup',[App\Http\Controllers\api\admin\admincontroller::class,'admin_signup']);
Route::post('admin_login',[App\Http\Controllers\api\admin\admincontroller::class,'admin_login']);
Route::middleware('CheckScopes:admin')->group(function(){
Route::get('admin_logout',[App\Http\Controllers\api\admin\admincontroller::class,'admin_logout']);
});
Route::post('admin_forget',[App\Http\Controllers\api\forgot\forgotpasswordcontroller::class,'admin_forget']);
Route::post('reset_admin_password/{token}',[App\Http\Controllers\Api\forgot\forgotpasswordcontroller::class,'reset_admin_password']);
Route::get('popular_course_list',[App\Http\Controllers\api\course\popularcourse::class,'popular_course_list']);
Route::get('top_category_list',[App\Http\Controllers\api\main_category\topcategory::class,'top_category_list']);
Route::get('latest_course_list',[App\Http\Controllers\api\course\latestcontroller::class,'latest_course_list']);
Route::post('course_type_filter',[App\Http\Controllers\api\filter\filtercontroller::class,'course_type_filter']);
Route::post('review_store',[App\Http\Controllers\api\review\reviewcontroller::class,'review_store']);
Route::get('review_list',[App\Http\Controllers\api\review\reviewcontroller::class,'review_list']);
Route::post('review_delete',[App\Http\Controllers\api\review\reviewcontroller::class,'review_delete']);
Route::post('subject_join',[App\Http\Controllers\api\join\joincontroller::class,'subject_join']);
Route::post('module_join',[App\Http\Controllers\api\join\joincontroller::class,'module_join']);
Route::post('lession_join',[App\Http\Controllers\api\join\joincontroller::class,'lession_join']);
});
